[build-system]
requires = ["jupyter_packaging>=0.10,<2", "jupyterlab==3.*", "setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "anywidget"
description = "custom jupyter widgets made easy"
authors = [
    { name = "Trevor Manz", email = "trevor.j.manz@gmail.com" }
]
license = { text = "MIT" }
dynamic = ["version"]
readme = "README.md"
dependencies = [
    "ipywidgets"
]

[project.optional-dependencies]
test = [
    "black[jupyter]",
    "pytest",
    "ruff==0.0.238"
]

[project.urls]
homepage = "https://github.com/manzt/anywidget"
